name: doc release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "git tag to release(this input is meaningless)"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Get Code

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000
      - name: Build Doc
        run: yarn run docs:build
      - name: Release Doc
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.