# this is from https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml

name: spa-client release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: ubuntu-latest
            name: linux-spa-client
            bash: make release-linux-client-musl
          - os: macos-latest
            name: mac-spa-client
            bash: make release-client-mac
          - os:  windows-latest
            name: windows-spa-client
            bash: make release-client-win
    runs-on: ${{ matrix.settings.os }}
    steps:
      - name: Get version
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.settings.os }}-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ matrix.settings.os }}-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup MUSL
        if: matrix.settings.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools

      - name: Build Release
        run: ${{ matrix.settings.bash }}


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./release/*
          name: ${{ matrix.settings.name }}
          if-no-files-found: error