name: spa-server-docker release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "version to release"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push spa-server
        uses: docker/build-push-action@v2
        with:
          context: .
          #platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: timzaak/spa-server:${{github.event.inputs.version}}

      - name: build and push spa-server with S3
        with:
          context: ./docker
          file: S3FS.Dockerfile
          push: true
          tags: timzaak/spa-server:${{github.event.inputs.version}}-s3