name: Publish Package to npmjs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: './jsclient/package-lock.json'
      - run: npm ci && npm build && npm publish
        working-directory: ./jsclient
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}