# this is from https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml
# this does not work now!
name: spa-client-cd

on:
#  push:
#    tags:
#      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "git tag to release"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get version
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{github.event.inputs.tag}}

      - name: Install Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Build
        run: cargo build

      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools

      - name: Build Release Mac
        if: matrix.os == 'macos-latest'
        run: make release-mac

      - name: Build Release Linux
        if: matrix.os == 'ubuntu-latest'
        run: make release-linux-musl

      - name: Build Release Win
        if: matrix.os == 'windows-latest'
        run: make release-win

      - name: Set SHA
        if: matrix.os == 'macos-latest'
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./release/gitui-mac.tar.gz | awk '{printf $1}')"
      - name: Extract release notes
        if: matrix.os == 'ubuntu-latest'
        id: release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            ./release/*.tar.gz
            ./release/*.zip
            ./release/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}